import React, { useEffect, useState } from "react";
import { Alert, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { COLORS } from "../../theme/colors";
import { chatApi } from "../../services/apiClient";
import { useUserStore } from "../../store/userStore";

const InAppChatScreen = ({ navigation, route }) => { const token = useUserStore((state) => state.token); const user = useUserStore((state) => state.user); const [messages, setMessages] = useState([]); const [text, setText] = useState(""); const roomId = route.params?.roomId; const [room, setRoom] = useState(route.params?.room); useEffect(() => { if (!roomId) return; chatApi.messages(token, roomId).then((data) => { setRoom(data.room); setMessages(data.messages || []); }).catch((error) => Alert.alert("Could not load chat", error.message)); }, [roomId, token]); const send = async () => { if (!text.trim()) return; const value = text.trim(); setText(""); try { const data = await chatApi.send(token, roomId, value); setMessages((current) => [...current, data.message]); } catch (error) { setText(value); Alert.alert("Message not sent", error.message); } }; return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>‹</Text></Pressable><View><Text style={styles.title}>Chat</Text><Text style={styles.subtitle}>Keep conversations and payments on O-Fash</Text></View></View><FlatList data={messages} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={[styles.bubble, item.senderId === user?.id ? styles.mine : styles.theirs]}><Text style={[styles.body, item.senderId === user?.id && styles.mineText]}>{item.body}</Text></View>} ListEmptyComponent={<Text style={styles.empty}>Start a safe conversation about this listing or order.</Text>} /><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} keyboardVerticalOffset={90} style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Write a message" placeholderTextColor={COLORS.faint} style={styles.input} maxLength={2000} /><Pressable onPress={send} style={styles.send}><Text style={styles.sendText}>Send</Text></Pressable></KeyboardAvoidingView></SafeAreaView>; };
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: COLORS.white }, header: { flexDirection: "row", alignItems: "center", gap: 12, padding: 16, borderBottomWidth: 1, borderColor: COLORS.line }, back: { fontSize: 30, color: COLORS.ink }, title: { fontSize: 15, fontWeight: "800", color: COLORS.ink }, subtitle: { fontSize: 8, color: COLORS.muted, marginTop: 3 }, list: { padding: 16, flexGrow: 1, justifyContent: "flex-end" }, bubble: { maxWidth: "78%", borderRadius: 16, padding: 11, marginVertical: 4 }, mine: { alignSelf: "flex-end", backgroundColor: COLORS.teal }, theirs: { alignSelf: "flex-start", backgroundColor: COLORS.surface }, body: { fontSize: 11, color: COLORS.ink, lineHeight: 16 }, mineText: { color: COLORS.white }, empty: { textAlign: "center", color: COLORS.muted, fontSize: 10, marginBottom: 25 }, composer: { flexDirection: "row", padding: 10, borderTopWidth: 1, borderColor: COLORS.line, gap: 8 }, input: { flex: 1, minHeight: 42, borderRadius: 21, backgroundColor: COLORS.surface, paddingHorizontal: 15, color: COLORS.ink }, send: { backgroundColor: COLORS.teal, borderRadius: 21, paddingHorizontal: 17, alignItems: "center", justifyContent: "center" }, sendText: { color: COLORS.white, fontWeight: "800", fontSize: 10 } });
export default InAppChatScreen;
