import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { RiderHeader } from "./RiderUi";
import { COLORS } from "../../theme/colors";

const Field = ({ label, value }) => <View style={styles.field}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>;
const RiderPersonalInfoScreen = ({ navigation }) => <SafeAreaView style={styles.safe}><RiderHeader title="PROFILE INFORMATION" back onBack={() => navigation.goBack()} /><ScrollView contentContainerStyle={styles.content}><View style={styles.switch}><Text style={styles.selected}>Personal info</Text><Text>Vehicle info</Text></View><Field label="FULL NAME" value="Chidi Olanrewaju" /><Field label="PHONE NUMBER" value="080 0000 0000" /><Field label="EMAIL ADDRESS" value="chidi.olanrewaju@gmail.com" /><Field label="DATE OF BIRTH" value="16th January 1998" /><Field label="GENDER" value="Male" /><Field label="NIN" value="******** 7888" /><Field label="ADDRESS" value="Lagos, Nigeria" /><Field label="VEHICLE" value="Bike" /><View style={styles.note}><Text style={styles.noteTitle}>Vehicle details</Text><Text style={styles.noteCopy}>Your vehicle information is used to match you with deliveries and calculate route capacity.</Text></View></ScrollView></SafeAreaView>;
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: COLORS.white }, content: { padding: 17, paddingBottom: 30 }, switch: { height: 30, borderRadius: 16, backgroundColor: COLORS.surface, flexDirection: "row", justifyContent: "space-around", alignItems: "center", marginBottom: 15 }, selected: { color: COLORS.white, backgroundColor: "#D43A0B", borderRadius: 14, paddingHorizontal: 25, paddingVertical: 6, fontSize: 7, fontWeight: "700" }, switchText: { fontSize: 7 }, field: { borderBottomWidth: 1, borderColor: COLORS.line, paddingVertical: 12 }, label: { color: COLORS.muted, fontSize: 6, fontWeight: "800", marginBottom: 5 }, value: { color: COLORS.ink, fontSize: 9 }, note: { backgroundColor: COLORS.tealSoft, borderRadius: 8, padding: 12, marginTop: 16 }, noteTitle: { color: COLORS.ink, fontWeight: "800", fontSize: 8 }, noteCopy: { color: COLORS.slate, fontSize: 7, lineHeight: 11, marginTop: 5 } });
export default RiderPersonalInfoScreen;
